### ISSUE TITLE
Indexing / slicing rather than unsafe offset/from_raw_parts?

### ISSUE THREAD

**Issue by SimonSapin** [japaric/heapless#1]
It seems like each `unsafe` block in this crate could be replaced with safe code indexing or slicing the result of `as_ref` or `as_mut`. Is there a reason to prefer the unsafe way?

**Comment by japaric** [comment]
Done in #4. `ring_buffer::{Consumer,Producer}` are still using unchecked indexing because otherwise LLVM is not able to optimize away the bound checks as per some tests I ran.
