### ISSUE TITLE
Did pool in an external crate break in the update?

### ISSUE THREAD

**Issue by korken89** [japaric/heapless#108]
I'm not 100% sure if I'm doing something wrong, but it seems that after the update `pool!` broke when used in an external crate and exported.

Simply creating a pool in crate X as:
```rust
use heapless::{
    pool,
    pool::singleton::Pool,
};

// ...

pool!(Mypool: [u8; 16]);
```

And trying to use is:
```rust
use X::Mypool;

// ...
Mypool::grow(MEMORY);
// ...
```

Gives the error:
```
the trait `heapless::pool::singleton::Pool` is not implemented for `X::Mypool`
```

This did not happen before the update and I am having issues circumventing the issue. Any ideas?
Thanks!

**Comment by burrbull** [comment]
It can be because as_slice depend on differ generic_array:
https://github.com/japaric/as-slice/pull/3
