### ISSUE TITLE
peek_mut for BinaryHeap?

### ISSUE THREAD

**Issue by equal-l2** [japaric/heapless#109]
`peek_mut` of std::collections::BinaryHeap is sometimes useful, for example we can use it to swap the top element of the heap efficiently, while we may require more time when using `pop` and `push` for that, because of `pop`.
I'd like to see that in heapless::BinaryHeap, too.

**Comment by korken89** [comment]
Hi @japaric - this seems as a very useful feature.
Do you see any issues with this/what interface to use? I could churn out the implementation for it.
I'm thinking something like:
```rust
myheap.update_top(|current_top| /* do changes to current top */ );
```

**Comment by korken89** [comment]
I did an implementation in https://github.com/japaric/heapless/pull/117

**Comment by japaric** [comment]
if the API is in `std::BinaryHeap` then you can just send a PR with the same API. This applies to all collections ported from `std`.

> I did an implementation in #117 

The `std` API also resorts the heap (in `PeekMut`'s destructor). Let's use that API instead of designing a new one.

**Comment by korken89** [comment]
Makes sense, I'll change to that

**Comment by korken89** [comment]
@japaric it's fixed now

**Comment by korken89** [comment]
Hi, this is now added!
However, I am unable to get the pop API to work and need to look into it:

```
Error[E0223]: ambiguous associated type
   --> src/neighbour/mod.rs:163:17
    |
163 |                 BinaryHeap::PeekMut::pop(value);
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^ help: use fully-qualified syntax: `<heapless::binary_heap::BinaryHeap<_, _, _> as Trait>::PeekMut`
```

**Comment by jonas-schievink** [comment]
Don't you want something like `binary_heap::PeekMut::pop` instead?

**Comment by korken89** [comment]
Haha, well this is awkward - that is exactly what needed to be done :)
Thanks for the hint!

**Comment by korken89** [comment]
I'll also close this as the requested feature has been added
