### ISSUE TITLE
Explain recommended strategy for moving data interrupt <-> main

### ISSUE THREAD

**Issue by birkenfeld** [japaric/heapless#111]
It would be nice to have a little more fleshed out info about the recommended ways to share data between interrupt handlers and the main program.  With the addition of Qxx, I assume that this is to be preferred, but its size limitation makes it not always applicable if items come in bursts and handling them can take a while.

Using Queue in such a context still requires `static mut` unsafe, and also it isn't explained if `split()` can be called in the main program in a way that it doesn't require `interrupt::free` to en/dequeue things.

Sorry, this is a bit rambly, but these are some of the things I was expecting to find in the docs, since this crate seems like it's tailored for these tasks.

**Comment by korken89** [comment]
This is usually up to the framework that is being used for resource handling.
E.g. RTIC has examples for how this should be done, while in the raw `cortex-m` world it's a bit more ambiguous with multiple different solutions.

**Comment by birkenfeld** [comment]
And it's not possible to mention those solutions? RTIC is very nice but feels always teetering in the brink of being abandoned, and I would wager that most people don't use it.

**Comment by korken89** [comment]
@birkenfeld here is an example: https://github.com/rtic-rs/cortex-m-rtic/blob/master/examples/late.rs

Not sure what you mean with that RTIC is being abandoned? It's actively maintained and developed.

**Comment by birkenfeld** [comment]
You're right - I guess pace has picked up again.
