### ISSUE TITLE
"Classic" ringbuffer support?

### ISSUE THREAD

**Issue by birkenfeld** [japaric/heapless#112]
I've needed a "classic" ringbuffer quite a few times now, and since it's not that hard rolled my own.  What I mean is:

* fixed capacity array plus index of "head"
* push() moves head and overwrites
* allows random access using iterator, and some standard things like first(), last()
* (maybe:) all items are initially filled with some default, allows getting rid of Option<>s for first() etc
* normal `&mut` methods, no lock-free support

This is nothing fancy, but seems like it falls under the mission statement of `heapless`?  I'll contribute an initial implementation PR, if yes.

**Comment by korken89** [comment]
Hi, the `Queue` seems to do what you want through the `Producer` and `Consumer` interface.
Or is there an issue there that you are facing?

**Comment by birkenfeld** [comment]
On a glance it seems similar to a Queue, but I need access to all elements without popping them.

Think a device with a noisy sensor that reads the sensor every millisecond and keeps the last N readings to make an average, minimum etc. calculations.

So the main differences to Queue are:

* access to all elements at any time, in exchange, no lock free characteristic required
* if full, oldest entries are just overwritten without needing to be popped
* (optional) always filled to capacity with a "null" value, see the last point in OP

**Comment by korken89** [comment]
Ah, I see. Lets see what @japaric says :)

**Comment by japaric** [comment]
Sorry for missing this issue.

This sounds reasonable to me. The `Default` bound to avoid the `Option` makes sense as well. 

> plus index of "head"

Is this is a push-only ring buffer?

> allows random access using iterator, and some standard things like first(), last()

Maybe also an `as_slice` method? To get access to all elements in arbitrary order. `rb.as_slice().iter().cloned().sum()` may eval faster than `rb.iter().cloned().sum()`.

**Comment by birkenfeld** [comment]
> Is this is a push-only ring buffer?

Yes. To avoid confusion with real ring buffers I've renamed it to `HistoryBuffer` in the PR. (Another name would be something with `Window`...)

> Maybe also an as_slice method?

I've implemented `AsSlice` and `AsMutSlice`.
