### ISSUE TITLE
Suggestion: consider exposing the Uxx and XCore traits for SPSC queues

### ISSUE THREAD

**Issue by rjsberry** [japaric/heapless#115]
It is currently not possible to be generic over the index type or single core/multi core SPSC queue variants because the traits `Uxx` and `XCore` can't be declared as type parameters because they are private.

If the traits were sealed so that the crate retained control over what types could implement `Uxx` and `XCore` it would be possible to write more generic code utilizing SPSC queues.

**Comment by bugadani** [comment]
I just hit a wall trying to implement a simple `flush` extension method so that I wouldn't need to loop 
like `while q.dequeue().is_some() {}` to flush a queue, because Uxx and XCore are not public. Shame
