### ISSUE TITLE
Serde support not working?

### ISSUE THREAD

**Issue by vagola** [japaric/heapless#116]
I am trying to derive structure and getting the following error:

```
the trait bound `heapless::string::String<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm, typenum::bit::B1>, typenum::bit::B0>, typenum::bit::B1>, typenum::bit::B0>, typenum::bit::B1>>: config::_IMPL_DESERIALIZE_FOR_Config::_serde::Deserialize<'_>` is not satisfied
```

It's strange because i see that heapless supports serde

**Comment by birkenfeld** [comment]
Serde support is optional; did you activate the `serde` feature for `heapless`?

**Comment by vagola** [comment]
In cargo.toml there are no features. How to enable it? Something like that `heapless = { version = "0.5", default-features = false, features = ["serde"] }`?

**Comment by birkenfeld** [comment]
Yes, that should work.

In heapless' `Cargo.toml` there is no explicit feature since the dependency is marked `optional = true`, which creates such a feature automatically.

**Comment by vagola** [comment]
Thanks for the help!
