### ISSUE TITLE
Vec/String in statics

### ISSUE THREAD

**Issue by burrbull** [japaric/heapless#122]
In https://github.com/japaric/heapless/commit/fc4054571fe68db5d541a5ca505217559d13a957 `const-fn` feature was removed.
And now I can't initialize static:
```
static mut V: Vec<U32> = Vec::new();
```

**Comment by birkenfeld** [comment]
You currently have to use `heapless::i``, see the example on https://japaric.github.io/heapless/heapless/index.html

**Comment by burrbull** [comment]
I thought, it is private. Sorry.
