### ISSUE TITLE
Implement `Write` trait for `Vec<u8, _>`

### ISSUE THREAD

**Issue by piegamesde** [japaric/heapless#124]
Please implement the `Write` trait for byte vectors. If possible, please also implement `Read`/`Write` for `Consumer`/`Producer` and other data structures.

**Comment by korken89** [comment]
Hi, I don't think I'm following.
The `io::Write` trait is std only do I don't see this as feasible.
Oh you had something else in mind, feel free to reopen

**Comment by piegamesde** [comment]
Plenty of crates offer `std` support behind a feature flag, where's the problem with that?

**Comment by korken89** [comment]
Ah I see, I don't have time to add this but if you feel like adding the support in a PR I'll have a look.
