### ISSUE TITLE
Heapless paper pdf?

### ISSUE THREAD

**Issue by aep** [japaric/heapless#146]
Is it possible to get access to the associated paper? "Heapless: Dynamic Data Structures without Dynamic Heap Allocator for Rust" somewhere?

**Comment by japaric** [comment]
Hello @aep. Sorry for the late reply.

I believe the paper can only be accessed if you have access to IEEE publications (?). @perlindgren would know better.

That paper was written before heapless v0.5.0 was released so the implementation covered there (v0.4.x) looks rather different than the current implementation (iirc, the version in the paper used the `CoerceUnsized` traits and required nightly).

Is there any particular question you had about that paper?

**Comment by aep** [comment]
well [zetz](https://github.com/zetzit/zz) is entirely heapless, so i'm interested in everything other people have written on the topic. In this case specifically i'm interested in anything you have learned that isn't obvious. Implementing stack based structures is pretty straight forward in zetz, but there are probably algos that fit better and some worse to being on the stack, when it comes to things like cache locality.

**Comment by perlindgren** [comment]
You can contact me personally, and I can share a copy of the paper (its behind a paywall).
