### ISSUE TITLE
Const generics

### ISSUE THREAD

**Issue by kpp** [japaric/heapless#168]
Const generics are getting more popular. I can try to implement `heapless` using const generics and push it into a separate branch until they are stable. It is a nice challenge both for coding skills and for const generics.
Shall I start?

**Comment by XOSplicer** [comment]
Reference  #102

**Comment by burrbull** [comment]
@kpp Try if you can.
9 months have passed since my last attempt. Maybe something has changed in good way.

**Comment by korken89** [comment]
@perlindgren has done the conversion, we are just awaiting stabilization to make a PR.

**Comment by kpp** [comment]
How about make a WIP PR so no one else tries to do it on their own?

**Comment by korken89** [comment]
@perlindgren Could you make a WIP PR with the conversion work you did?

**Comment by korken89** [comment]
For reference the work is being done here: https://github.com/perlindgren/heapless/tree/const_generics

**Comment by perlindgren** [comment]
Everything is implemented and the code passes all tests.

There are some type bounds that needs to be added for ensuring power 2, I don't recall exactly. These were provided by GenericArray previously, not sure if we want to define/implement them ourselves, or if these are available elsewhere.

**Comment by tarcieri** [comment]
Perhaps I should ask on the `as-slice` repo, but there is a plan for it and const generics?

I ask because as of #189 `heapless` is now pulling in three versions of `generic-array` (v0.12, v0.13, v0.14)

**Comment by korken89** [comment]
Technically, when const generics lands, all code related to `generic-array` will disappear as there is no longer any need for it.
This is also what we have done in the port of `heapless`. For `as-slice` I will do the same and remove all the code related to `generic-array` and specific array size implementations.

**Comment by burrbull** [comment]
8 days before beta.

**Comment by burrbull** [comment]
Time

**Comment by korken89** [comment]
Here you can follow the work, we almost finished the port https://github.com/japaric/heapless/tree/const_generics
