### ISSUE TITLE
Vector .resize() broken

### ISSUE THREAD

**Issue by viktorfrom** [japaric/heapless#169]
Hello.  while working on a project I may have found a potential bug with .resize(&mut self, new_len: usize, value: T). When the following code is executed there is no change in the capacity of the vector. 

```
let mut data: Vec<u8, U1> = Vec::new();
hprintln!("data = {:#?}", data.capacity());
data.resize(10, 0);
hprintln!("data = {:#?}", data.capacity());
```

Correct me if I'm wrong but I believe this should work in the same way as std, right?

**Comment by XOSplicer** [comment]
Hi, 

`data.capacity()`  will report the _maximum_ available capacity of the vector, which is determined by the constant generic number. In the example `U1`, therefore the capacity is always `1`. This is determined statically and will not change at runtime.

`data.resize(new_len, value)` _tries_ to resize the vector to the new lenght by filling it with `value`. This is a failable operation as the vector can not be resized to be larger than its capacity. `data.resize(...)` will therefore return a `Result`.

This behavior is different from `std`, as this create does not use an allocator to increase the capacity of the vector at runtime.
