### ISSUE TITLE
Defmt support

### ISSUE THREAD

**Issue by theunkn0wn1** [japaric/heapless#171]
I recently discovered the [`defmt`](https://github.com/knurling-rs/defmt)  library and attempted to integrate it into one of my embedded projects.

Unfortunately it appears that `heapless::Vec` doesn't implement the `defmt::Format` trait yet, which blocks `defmt` integration in my downstream. 

Feature request: support for `defmt::Format` in `heapless::Vec`

**Comment by korken89** [comment]
Hi, I have commented on the PR itself.

**Comment by korken89** [comment]
Available in 0.7.1

**Comment by mehmetalianil** [comment]
I get `error: unknown display hint: "[u8]"`  from:
```rust
let mut test_vec: Vec<u8, 128> = Vec::new();
   ... 
info!("the vector: {:[u8]}", test_vec);
```

Am I mistaken with the format specifier?

**Comment by korken89** [comment]
Have you enabled the feature flag?

**Comment by theunkn0wn1** [comment]
In my testing i used `{:?}` and `{=[?]}`, which both compile.

```rs
        let mut data: Vec<u32, 16> = Vec::new();
        data.push(0x42).expect("Failed to push into vec...");
        data.push(0x50).expect("Failed to push into vec...");
        data.push(0x10).expect("Failed to push into vec...");

        defmt::debug!("Writing data....");
        defmt::info!("{=[?]}", data);
        defmt::debug!("populating string...");
        let string: String<32> = String::from("I like pizza");
        defmt::debug!("Emitting string...");
        defmt::info!("{:?}", string);

```
