### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jamessewell** [japaric/heapless#176]
Just wondering when / if  a new release is expected?

I need https://github.com/japaric/heapless/pull/154, and packaging with Cargo.toml links to github is problematic! 

Thanks for the amazing crate!

**Comment by korken89** [comment]
Hi, the PR is up and awaiting review: https://github.com/japaric/heapless/pull/175

**Comment by korken89** [comment]
Released :)

**Comment by eeeebbbbrrrr** [comment]
Fantastic!  Much thanks!
