### ISSUE TITLE
Failure to build on AVR due to missing atomic types

### ISSUE THREAD

**Issue by Palladinium** [japaric/heapless#179]
I'm trying to build a project for the Atmega 328p but I'm hitting an error while compiling `heapless`

# Error

```
error[E0432]: unresolved imports `core::sync::atomic::AtomicU16`, `core::sync::atomic::AtomicUsize`
 --> /home/patrick/.cargo/git/checkouts/heapless-9de3abde4d9bcaa0/9ff3a5f/src/sealed.rs:7:36
  |
7 |     use core::sync::atomic::{self, AtomicU16, AtomicU8, AtomicUsize, Ordering};
  |                                    ^^^^^^^^^            ^^^^^^^^^^^ no `AtomicUsize` in `sync::atomic`
  |                                    |
  |                                    no `AtomicU16` in `sync::atomic`
  |                                    help: a similar name exists in the module: `AtomicU8`
```

# Reproduction steps
Same as for #177

# Versions
rustc 1.48.0-nightly (e599b53e6 2020-09-24)
heapless commit 9ff3a5fa (latest master as of writing)
avr-atmega328p.json from https://github.com/Rahix/avr-hal, commit 2a59d441 (latest master as of writing)

# Workaround

I was able to compile after adding `avr-atmega328p` to the `rustc-cfg=has_atomics` check in `build.rs`, but I'm not sure if that's the correct way to go about it since the target isn't built-in yet.

**Comment by korken89** [comment]
Hi, what is needed for this is that the target has atomics.
If the system has atomics it's safe to add it to the check.

I have no experience with AVR, so I am unable to say if this condition holds for AVR.
