### ISSUE TITLE
Unsoundness in vec::IntoIter::clone()

### ISSUE THREAD

**Issue by Dirbaio** [japaric/heapless#181]
`IntoIter`'s Clone implementation clones the entire inner Vec. If the iterator has been partially consumed, only the non-consumed items should be cloned.

The following code demonstrates the issue:

```rust
use heapless::consts::*;
use heapless::Vec;

#[derive(Debug)]
struct Foo {
    n: u32,
}

impl Foo {
    fn new(n: u32) -> Self {
        Self { n }
    }
}

impl Clone for Foo {
    fn clone(&self) -> Self {
        println!("cloning {:?}", self);
        Self {
            n: self.n,
        }
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        println!("Dropping {:?}", self);
    }
}

fn main() {
    println!("Hello, world!");
    let mut v: Vec<Foo, U16> = Vec::new();
    v.push(Foo::new(1)).unwrap();
    v.push(Foo::new(2)).unwrap();
    v.push(Foo::new(3)).unwrap();

    let mut i = v.into_iter();

    let item = i.next();
    println!("popped {:?}", item);
    core::mem::drop(item);

    println!("cloning iter");

    let mut j = i.clone();
}
```

This outputs

```
Hello, world!
popped Some(Foo { n: 1 })
Dropping Foo { n: 1 }
cloning iter
cloning Foo { n: 1 }
cloning Foo { n: 2 }
cloning Foo { n: 3 }
Dropping Foo { n: 2 }
Dropping Foo { n: 3 }
Dropping Foo { n: 2 }
Dropping Foo { n: 3 }
```

After `Foo 1` is popped from the iterator, cloning the iterator will still clone the "dead" `Foo 1`. Only `Foo 2` and `Foo 3` should be cloned.

**Comment by Shnatsel** [comment]
Heads up: this issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

Once a fix is released to crates.io, please open a pull request to update the advisory with the patched version, or file an issue on [the advisory database repository](https://github.com/RustSec/advisory-db).

**Comment by korken89** [comment]
Fixed in #195

**Comment by korken89** [comment]
Now released as 0.6.1

**Comment by korken89** [comment]
And the PR is merged: https://github.com/RustSec/advisory-db/pull/791/files

**Comment by Shnatsel** [comment]
Thank you!
