### ISSUE TITLE
CI is gone

### ISSUE THREAD

**Issue by korken89** [japaric/heapless#184]
It seems that Travis has shut down?
We need to move this repo to Github Actions.

**Comment by japaric** [comment]
I was poking at my travis settings and probably broke this, sorry. but yes travis-ci.org is being shut down. people should migrate to travis-ci.com . the latter has monthly quotas for macOS builds though.

we should move to GitHub Actions, IMO

**Comment by korken89** [comment]
I was talking to Henrik (that is also helping on RTIC) and we will fix it over to GHA over the coming days :)
