### ISSUE TITLE
Can Vecs Contain an Enum Type?

### ISSUE THREAD

**Issue by kkevlar** [japaric/heapless#190]
Hi all, 

Quick question. Should the Vec type be able to contain a user defined enum type, or only the builtin numeric types as shown in the documentation.

Thank you for your help.

**Comment by burrbull** [comment]
Yes, if enum implements `Copy`.

**Comment by korken89** [comment]
Hi, `Copy` is not required.

See here for the interface of `push`: https://github.com/japaric/heapless/blob/4afa223fbea1ffad5045bc4cb7d02d59db3cbb0c/src/vec.rs#L270
Some special methods require `Clone` and I think one method requires `Copy`.
But all in all, yes `Vec` supports any `Sized` type :)

**Comment by kkevlar** [comment]
Thanks!
