### ISSUE TITLE
Queue with capacity 1 is both empty and full

### ISSUE THREAD

**Issue by jonas-schievink** [japaric/heapless#214]
```rust
use heapless::spsc::Queue;

fn main() {
    let queue: Queue<[u8; 16], 1> = Queue::new();
    assert!(queue.is_empty());
    assert!(!queue.is_full());
}
```

```
thread 'main' panicked at 'assertion failed: !queue.is_full()', src/main.rs:6:5
```

**Comment by birkenfeld** [comment]
From the docs: "A statically allocated single producer single consumer queue with a capacity of N - 1 elements".  This is, I think, because the needed const generic math to allocate `N + 1` items is not stable yet.

Is it possible to statically assert `N > 1`?

**Comment by jonas-schievink** [comment]
Oh, I see, I missed that

**Comment by birkenfeld** [comment]
It's new in 0.7 (the first const generics based version).

**Comment by burrbull** [comment]
> Is it possible to statically assert `N > 1`?

In nightly only.

**Comment by korken89** [comment]
Hi, it's possible to do asserts in const with some tricks.
https://github.com/nvzqz/static-assertions-rs/issues/40#issuecomment-846228355

I'll look into adding them everywhere.

**Comment by korken89** [comment]
Yeah, the interface is a bit unfortunate.
I hope we get more const power soon so we can get the old interface back.
