### ISSUE TITLE
evaluation of constant value failed

### ISSUE THREAD

**Issue by MathiasKoch** [japaric/heapless#216]
With the newly released 0.7.2, i am getting

```
error[E0080]: evaluation of constant value failed
  --> .../github.com-1ecc6299db9ec823/heapless-0.7.2/src/sealed.rs:56:32
   |
56 |     pub const GREATER: usize = L - R - 1;
   |                                ^^^^^^^^^ attempt to compute `0_usize - 1_usize`, which would overflow

error: aborting due to previous error; 7 warnings emitted

```

**Comment by korken89** [comment]
This is the new const assert failing.
Either you have a Queue with N == 0 or 1 or a Vec with N == 0.
This will cause the data structures to misbehave add it's below the minimum sizes of each.

I added these checks to highlight this issue to users.

**Comment by korken89** [comment]
Also note the new size definition for Queue, size = N - 1 until we get more const powers and get back the old interface

**Comment by MathiasKoch** [comment]
Found it.. Had a `String<0>` in my code. Thanks for the assistance!
