### ISSUE TITLE
spsc queue of size 1 fails to compile

### ISSUE THREAD

**Issue by tdaede** [japaric/heapless#228]
```
static mut CONFIG_QUEUE: Queue<u8, 1> = Queue::new();
```

```
error[E0080]: evaluation of `heapless::sealed::Assert::<1_usize, 1_usize>::GREATER` failed
  --> /home/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/heapless-0.7.4/src/sealed.rs:56:32
   |
56 |     pub const GREATER: usize = L - R - 1;
   |                                ^^^^^^^^^ attempt to compute `0_usize - 1_usize`, which would overflow
```

I have a couple of cases where a queue of length 1 is useful (there are arguably better data structures for that, though not in heapless)

**Comment by korken89** [comment]
Hi,

Please refer to the documentation which states that the size of the queue is N - 1.
So to get a size 1 queue you need to put a 2.

This is an unfortunate limitation due to const generics that will be changed once we can do math on const generics.
