### ISSUE TITLE
Sync Pool support for i686

### ISSUE THREAD

**Issue by japaric** [japaric/heapless#231]
The `x86-sync-pool` Cargo feature lets you use the `pool!` macro on x86_64 with the caveat that it has a small probability of running into Undefined Behavior (UB). The main use case of `x86-sync-pool` are *short-lived* tests running on a time-sliced scheduled (e.g. Linux). Using `x86-sync-pool` on a long lived process or a process that uses prioritized threads has a high(er) chance of running into UB.

Because Rust does not support / expose 128-bit atomics (the x86_64 architecture supports them natively) the x86_64 implementation uses a 64-bit atomic to store *both* a 32-bit pointer and a 32-bit 'version tag'. The downside of using a 64-bit atomic is that the memory addresses that the `Pool` can manage are limited to +- 2 GB around some `ANCHOR` address. This `ANCHOR` is placed in `.bss` so the `Pool` may not be able to manage heap allocated (e.g. `std::Box`) memory: any memory outside the 4GB space around `ANCHOR` will be silently "dropped" (leaked).

A practical solution to this problem is to run a 32-bit version of the program on the x86_64 processor, e.g. using `cargo run --target i686-linux-unknown-musl`. When using 32-bit mode on x86_64 the OS will memory map available (RAM) memory to a 32-bit memory space; this removes the need for an `ANCHOR` address in the implementation. The i686 supports `AtomicU64` so that can be used to store a 32-bit pointer plus the 32-bit version tag in a i686 `Pool` implementation. Using a 32-bit version of `Pool` on a x86_64 processor does not change (increase or reduce) the probability of running into the ABA problem (UB).

**Comment by korken89** [comment]
Sounds good, feel free to implement it!
