### ISSUE TITLE
mpmc only works with sizes that are power of 2

### ISSUE THREAD

**Issue by chemicstry** [japaric/heapless#243]
This goes into an endless loop on dequeue:
```
let q = mpmc::MpMcQueue::<i32, 3>::new();
q.enqueue(0).unwrap();
q.enqueue(1).unwrap();
q.enqueue(0).unwrap();
q.dequeue().unwrap();
```

This panics:
```
let q = mpmc::MpMcQueue::<i32, 6>::new();
q.enqueue(0).unwrap();
q.enqueue(1).unwrap();
q.enqueue(0).unwrap();
q.enqueue(1).unwrap();
q.enqueue(0).unwrap();
q.enqueue(1).unwrap();
q.dequeue().unwrap();
```

[Original implementation](https://www.1024cores.net/home/lock-free-algorithms/queues/bounded-mpmc-queue) seems to have an assert for power of 2. So if that's an implementation requirement it would be nice to mention in the docs and add an assert.

I can submit a PR someday, if nobody fixes this until then

**Comment by korken89** [comment]
Thanks for finding!
Indeed it needs powers of 2, I think it got lost in the great `const generics` rewrite.
