### ISSUE TITLE
Implement `FromIterator` for `String`

### ISSUE THREAD

**Issue by harrier-lcc** [japaric/heapless#245]
Is it possible to include `FromIterator<char>` or maybe other fromiterators from `alloc::string::String` API for `heapless::String`? 

This will greatly enhance String usability as in many case one will need to build String from char / u8.

**Comment by korken89** [comment]
I don't see any issue with that, feel like making a PR?

**Comment by japaric** [comment]
implemented in PR #274. will be available in the v0.7.12 release
