### ISSUE TITLE
Emit compiler error if capacity of IndexMap is not power of 2

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [japaric/heapless#257]
I was using heapless when working on Advent Of Code solutions and set the capacity of an IndexMap to a value that is not a power of 2, and it caused the indexmap to silently return incorrect results or fail to look up keys. It took me a while to figure out what to problem was. I think it would be very beneficial to emit a compiler warning or error if the capacity parameter is not a power of 2.

**Comment by korken89** [comment]
Thanks for noticing! I'll add the const assert for it.

**Comment by darkwater** [comment]
Using `Default::default()` to get an IndexMap will still work without error. Maybe you can call to `IndexMap::new()` from there?
