### ISSUE TITLE
[feature] Make Deque::pop_{front,back}_unchecked public

### ISSUE THREAD

**Issue by danielzfranklin** [japaric/heapless#268]
I'm iterating through the deque to peek, and then popping everything I peeked at if I'm ready to consume the bytes. In this case I know that I can soundly pop unchecked.

Currently `Deque::pop_{front,back}_unchecked` are private. Both seem to have sufficient docs to be made public without any changes. Is there a reason they should be private?

**Comment by japaric** [comment]
the methods will be public in release v0.7.12. note that, in general, you can use the [`unreachable_unchecked`](https://doc.rust-lang.org/core/hint/fn.unreachable_unchecked.html) API to remove runtime checks from checked methods.
