### ISSUE TITLE
compile on stable

### ISSUE THREAD

**Issue by japaric** [japaric/heapless#40]
Off the top of my head these things need to be done to get this compiling on stable:

- Put all `const` functions behind a `const-fn` feature.

- Put the generic atomic type (`Atomic<T>`) behind a Cargo feature. `AtomicUsize` should be used everywhere when that feature is disabled.

- Remove the `nonzero` feature ( `NonZeroU32`) in favor of manually checking for some magic value that represents `None`.

**Comment by XOSplicer** [comment]
I might look into the `const-fn` feature gate, when I find the time this week.

**Comment by XOSplicer** [comment]
Removing `NonZeroU32` is ready in #50.
When no default features are enables, heapless now compiles on stable rust.
