### ISSUE TITLE
Improve / refactor `RingBuffer` iterators

### ISSUE THREAD

**Issue by japaric** [japaric/heapless#6]
The implementation of `ring_buffer::{Iter,IterMut}` is pretty much a copy of the other. The duplication can be eliminated by using a macro (see implementation of iterators in libcore). Also both `Iter` and `IterMut` use the default methods provided by the `Iterator` trait; the `Iterator` implementation for those two could override the default methods for better performance.

**Comment by japaric** [comment]
Triage: Still needs to be implemented.

**Comment by XOSplicer** [comment]
Hi @japaric, 
check out https://github.com/XOSplicer/heapless/commit/57452a8138f70eeeb8bffcef51b1a870286cf06c if you have the time.
I have never worked with macros before, so some things might be a little rough.
If you like the changes, I can open a PR.
